import pytest

from pgmig import generate
from tests.api.generate_setup import GenerateSetup


def test_serial_column_emitted_as_serial(gen_setup: GenerateSetup) -> None:
    """
    A serial column is emitted with the `serial` pseudo-type, not its expanded
    integer + nextval() default. The owned backing sequence stays excluded, so
    the emitted CREATE TABLE is self-contained and can be applied on its own.
    """
    gen_setup.assert_diff(
        src=[],
        dst=["CREATE TABLE person (id serial)"],
        diff=['CREATE TABLE "public"."person" ("id" serial)'],
    )


def test_bigserial_column_emitted_as_bigserial(gen_setup: GenerateSetup) -> None:
    """
    A bigserial (int8) column is emitted with the `bigserial` pseudo-type.
    """
    gen_setup.assert_diff(
        src=[],
        dst=["CREATE TABLE person (id bigserial)"],
        diff=['CREATE TABLE "public"."person" ("id" bigserial)'],
    )


def test_smallserial_column_emitted_as_smallserial(gen_setup: GenerateSetup) -> None:
    """
    A smallserial (int2) column is emitted with the `smallserial` pseudo-type.
    """
    gen_setup.assert_diff(
        src=[],
        dst=["CREATE TABLE person (id smallserial)"],
        diff=['CREATE TABLE "public"."person" ("id" smallserial)'],
    )


def test_serial_column_with_primary_key_and_other_column(gen_setup: GenerateSetup) -> None:
    """
    A serial column alongside a plain column and a primary key: the serial type is
    emitted inline, the plain column unchanged, and the primary key added after.
    """
    gen_setup.assert_diff(
        src=[],
        dst=["CREATE TABLE person (id serial PRIMARY KEY, name text)"],
        diff=[
            'CREATE TABLE "public"."person" ("id" serial, "name" text)',
            'ALTER TABLE "public"."person" ADD CONSTRAINT "person_pkey" PRIMARY KEY (id)',
        ],
    )


def test_identity_by_default_column_emitted(gen_setup: GenerateSetup) -> None:
    """
    A GENERATED BY DEFAULT AS IDENTITY column is emitted with its identity clause
    inline. The identity implies NOT NULL and owns its backing sequence, so the
    emitted CREATE TABLE is self-contained and converges on apply.
    """
    gen_setup.assert_diff(
        src=[],
        dst=["CREATE TABLE person (id integer GENERATED BY DEFAULT AS IDENTITY)"],
        diff=['CREATE TABLE "public"."person" ("id" integer GENERATED BY DEFAULT AS IDENTITY)'],
    )


def test_identity_always_column_emitted(gen_setup: GenerateSetup) -> None:
    """
    A GENERATED ALWAYS AS IDENTITY column ('a') is emitted with the ALWAYS clause,
    distinct from BY DEFAULT ('d').
    """
    gen_setup.assert_diff(
        src=[],
        dst=["CREATE TABLE person (id bigint GENERATED ALWAYS AS IDENTITY)"],
        diff=['CREATE TABLE "public"."person" ("id" bigint GENERATED ALWAYS AS IDENTITY)'],
    )


def test_identity_column_added_to_existing_table(gen_setup: GenerateSetup) -> None:
    """
    Adding an identity column to a table present on both sides emits ADD COLUMN with
    the identity clause inline.
    """
    gen_setup.assert_diff(
        both=["CREATE TABLE person (name text)"],
        src=[],
        dst=["ALTER TABLE person ADD COLUMN id integer GENERATED ALWAYS AS IDENTITY"],
        diff=['ALTER TABLE "public"."person" ADD COLUMN "id" integer GENERATED ALWAYS AS IDENTITY'],
    )


def test_serial_change_in_alter_path_raises(gen_setup: GenerateSetup) -> None:
    """
    A shared column changing between plain integer and serial is unsupported. The type
    stays 'integer', so the type/identity guards do not fire; without a serial guard the
    diff would emit SET DEFAULT nextval('..._seq') referencing an owned sequence that is
    excluded from introspection and never created -> apply fails "relation does not
    exist". It must raise instead.
    """
    gen_setup.src.execute("CREATE TABLE person (id integer)")
    gen_setup.dst.execute("CREATE TABLE person (id serial)")

    with pytest.raises(NotImplementedError, match="serial change"):
        generate(source=gen_setup.src.dsn, target=gen_setup.dst.dsn)
