from tests.fixtures.generate_setup import GenerateSetup


def test_serial_column_emitted_as_serial(gen_setup: GenerateSetup) -> None:
    """
    A serial column is emitted with the `serial` pseudo-type, not its expanded
    integer + nextval() default. The owned backing sequence stays excluded, so
    the emitted CREATE TABLE is self-contained and can be applied on its own.
    """
    gen_setup.dst.execute("CREATE TABLE person (id serial)")

    gen_setup.assert_migration_sql('CREATE TABLE "public"."person" ("id" serial);')


def test_bigserial_column_emitted_as_bigserial(gen_setup: GenerateSetup) -> None:
    """
    A bigserial (int8) column is emitted with the `bigserial` pseudo-type.
    """
    gen_setup.dst.execute("CREATE TABLE person (id bigserial)")

    gen_setup.assert_migration_sql('CREATE TABLE "public"."person" ("id" bigserial);')


def test_smallserial_column_emitted_as_smallserial(gen_setup: GenerateSetup) -> None:
    """
    A smallserial (int2) column is emitted with the `smallserial` pseudo-type.
    """
    gen_setup.dst.execute("CREATE TABLE person (id smallserial)")

    gen_setup.assert_migration_sql('CREATE TABLE "public"."person" ("id" smallserial);')


def test_serial_column_with_primary_key_and_other_column(gen_setup: GenerateSetup) -> None:
    """
    A serial column alongside a plain column and a primary key: the serial type is
    emitted inline, the plain column unchanged, and the primary key added after.
    """
    gen_setup.dst.execute("CREATE TABLE person (id serial PRIMARY KEY, name text)")

    gen_setup.assert_migration_sql(
        [
            'CREATE TABLE "public"."person" ("id" serial, "name" text);',
            'ALTER TABLE "public"."person" ADD CONSTRAINT "person_pkey" PRIMARY KEY (id);',
        ]
    )


def test_identity_column_not_treated_as_serial(gen_setup: GenerateSetup) -> None:
    """
    A GENERATED ... AS IDENTITY column is not a serial column: it must not be
    rewritten to the `serial` pseudo-type (serial detection excludes identity).
    """
    gen_setup.dst.execute("CREATE TABLE person (id integer GENERATED BY DEFAULT AS IDENTITY)")

    gen_setup.assert_migration_sql('CREATE TABLE "public"."person" ("id" integer NOT NULL);')
