import pytest

from pgmig import generate
from tests.fixtures.generate_setup import GenerateSetup


def test_serial_column_emitted_as_serial(gen_setup: GenerateSetup) -> None:
    """
    A serial column is emitted with the `serial` pseudo-type, not its expanded
    integer + nextval() default. The owned backing sequence stays excluded, so
    the emitted CREATE TABLE is self-contained and can be applied on its own.
    """
    gen_setup.dst.execute("CREATE TABLE person (id serial)")

    gen_setup.assert_migration_sql('CREATE TABLE "public"."person" ("id" serial);')


def test_bigserial_column_emitted_as_bigserial(gen_setup: GenerateSetup) -> None:
    """
    A bigserial (int8) column is emitted with the `bigserial` pseudo-type.
    """
    gen_setup.dst.execute("CREATE TABLE person (id bigserial)")

    gen_setup.assert_migration_sql('CREATE TABLE "public"."person" ("id" bigserial);')


def test_smallserial_column_emitted_as_smallserial(gen_setup: GenerateSetup) -> None:
    """
    A smallserial (int2) column is emitted with the `smallserial` pseudo-type.
    """
    gen_setup.dst.execute("CREATE TABLE person (id smallserial)")

    gen_setup.assert_migration_sql('CREATE TABLE "public"."person" ("id" smallserial);')


def test_serial_column_with_primary_key_and_other_column(gen_setup: GenerateSetup) -> None:
    """
    A serial column alongside a plain column and a primary key: the serial type is
    emitted inline, the plain column unchanged, and the primary key added after.
    """
    gen_setup.dst.execute("CREATE TABLE person (id serial PRIMARY KEY, name text)")

    gen_setup.assert_migration_sql(
        [
            'CREATE TABLE "public"."person" ("id" serial, "name" text);',
            'ALTER TABLE "public"."person" ADD CONSTRAINT "person_pkey" PRIMARY KEY (id);',
        ]
    )


def test_identity_column_raises_not_serial(gen_setup: GenerateSetup) -> None:
    """
    A GENERATED ... AS IDENTITY column is not a serial column and is not yet modelled.
    Emitting it as a plain column would silently drop the identity (a migration that
    never converges), so creating one raises rather than being coerced.
    """
    gen_setup.dst.execute("CREATE TABLE person (id integer GENERATED BY DEFAULT AS IDENTITY)")

    with pytest.raises(NotImplementedError, match="Identity column"):
        generate(source=gen_setup.src.dsn, target=gen_setup.dst.dsn)


def test_serial_change_in_alter_path_raises(gen_setup: GenerateSetup) -> None:
    """
    A shared column changing between plain integer and serial is unsupported. The type
    stays 'integer', so the type/identity guards do not fire; without a serial guard the
    diff would emit SET DEFAULT nextval('..._seq') referencing an owned sequence that is
    excluded from introspection and never created -> apply fails "relation does not
    exist". It must raise instead.
    """
    gen_setup.src.execute("CREATE TABLE person (id integer)")
    gen_setup.dst.execute("CREATE TABLE person (id serial)")

    with pytest.raises(NotImplementedError, match="serial change"):
        generate(source=gen_setup.src.dsn, target=gen_setup.dst.dsn)
