from tests._api.generate_setup import GenerateSetup


def test_add_identity_to_plain_column(gen_setup: GenerateSetup) -> None:
    """
    A plain, nullable column gaining an identity: ADD ... AS IDENTITY requires the column
    to be NOT NULL first, so SET NOT NULL is emitted before the ADD.
    """
   await gen_setup.assert_diff(
        src=["CREATE TABLE person (id integer)"],
        dst=["CREATE TABLE person (id integer GENERATED ALWAYS AS IDENTITY)"],
        diff=[
            'ALTER TABLE "public"."person" ALTER COLUMN "id" SET NOT NULL',
            'ALTER TABLE "public"."person" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY',
        ],
    )


def test_drop_identity_to_plain_column(gen_setup: GenerateSetup) -> None:
    """
    An identity column losing its identity -> DROP IDENTITY. DROP IDENTITY leaves the
    column NOT NULL, so a nullable target also needs DROP NOT NULL, emitted after.
    """
   await gen_setup.assert_diff(
        src=["CREATE TABLE person (id integer GENERATED ALWAYS AS IDENTITY)"],
        dst=["CREATE TABLE person (id integer)"],
        diff=[
            'ALTER TABLE "public"."person" ALTER COLUMN "id" DROP IDENTITY',
            'ALTER TABLE "public"."person" ALTER COLUMN "id" DROP NOT NULL',
        ],
    )


def test_identity_always_to_by_default(gen_setup: GenerateSetup) -> None:
    """
    ALWAYS -> BY DEFAULT is a generation-kind flip -> SET GENERATED BY DEFAULT.
    """
   await gen_setup.assert_diff(
        src=["CREATE TABLE person (id integer GENERATED ALWAYS AS IDENTITY)"],
        dst=["CREATE TABLE person (id integer GENERATED BY DEFAULT AS IDENTITY)"],
        diff=['ALTER TABLE "public"."person" ALTER COLUMN "id" SET GENERATED BY DEFAULT'],
    )


def test_identity_by_default_to_always(gen_setup: GenerateSetup) -> None:
    """
    BY DEFAULT -> ALWAYS is the reverse generation-kind flip -> SET GENERATED ALWAYS.
    """
   await gen_setup.assert_diff(
        src=["CREATE TABLE person (id integer GENERATED BY DEFAULT AS IDENTITY)"],
        dst=["CREATE TABLE person (id integer GENERATED ALWAYS AS IDENTITY)"],
        diff=['ALTER TABLE "public"."person" ALTER COLUMN "id" SET GENERATED ALWAYS'],
    )


def test_serial_to_identity(gen_setup: GenerateSetup) -> None:
    """
    Converting a serial column to an identity column (recommended modern practice).
    The serial nextval() default must be dropped before ADD IDENTITY (Postgres refuses
    ADD IDENTITY on a column that still has a default). The old serial-owned sequence
    lingers but is excluded from introspection, so the migration still converges.
    """
   await gen_setup.assert_diff(
        src=["CREATE TABLE person (id serial)"],
        dst=["CREATE TABLE person (id integer GENERATED BY DEFAULT AS IDENTITY)"],
        diff=[
            'ALTER TABLE "public"."person" ALTER COLUMN "id" DROP DEFAULT',
            'ALTER TABLE "public"."person" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY',
        ],
    )


def test_plain_with_default_to_identity_drops_default_first(gen_setup: GenerateSetup) -> None:
    """
    A plain column carrying a default that becomes an identity: DROP DEFAULT must precede
    ADD IDENTITY, otherwise Postgres refuses the ADD.
    """
   await gen_setup.assert_diff(
        src=["CREATE TABLE person (id integer DEFAULT 5)"],
        dst=["CREATE TABLE person (id integer GENERATED ALWAYS AS IDENTITY)"],
        diff=[
            'ALTER TABLE "public"."person" ALTER COLUMN "id" DROP DEFAULT',
            'ALTER TABLE "public"."person" ALTER COLUMN "id" SET NOT NULL',
            'ALTER TABLE "public"."person" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY',
        ],
    )


def test_identity_to_serial_raises(gen_setup: GenerateSetup) -> None:
    """
    Converting an identity column to serial is unsupported: the serial backing sequence
    is excluded from introspection, so a SET DEFAULT nextval('..._seq') would reference a
    sequence that is never created. It must raise rather than emit a non-converging diff.
    """
    gen_setup.assert_unsupported(
        src=["CREATE TABLE person (id integer GENERATED BY DEFAULT AS IDENTITY)"],
        dst=["CREATE TABLE person (id serial)"],
        match="serial change",
    )
